### ISSUE TITLE
No feasible solution

### ISSUE THREAD

**Issue by raczmate** [Uni-Sopron/temelesiranyitas-o22-timewindow-vrp#1]
Mit ronthattam el?

**Comment by hegyhati** [comment]
Az elso kerdes az, hogy a modellt Te talaltad ki, vagy valahonnet szedted / alapszik valamire, amit valahol olvastal? Utobbi esetben illik citalni (md-ben). Illetve az adathalmaz biztos olyan, hogy van feasible megoldas? Tudsz kezzel mutatni feasible-t? Ha igen, a hiba felderitesere egy jo modszer, hogy "beegeted" azt a megoldast (kulcsfontossagu valtozokat ideiglenesen lerogzitesz korlatozasokkal) es megnezed melyik alap korlatozas kikommentezese utan lesz feasible a megoldas. Es akkor ott van valami gubanc valoszinuleg.

**Comment by raczmate** [comment]
Köszönöm szépen a visszajelzést!
Igen, a modell ebben a reportban található modellen alapszik: 
http://www.aui.ma/sse-capstone-repository/pdf/spring-2017/OumaymaGrineVehicleRoutingProblemFinalReport.pdf
Feasible megoldást tudtam csinálni egyszer a BigM-es korlátozás kikommentezésével. Mindenképpen tovább fogok próbálkozni!

**Comment by hegyhati** [comment]
Okok, akkor rakd bele az md-be. 
Es lehet jo a modell, csak lehet az input adatok olyanok, hogy nincs feasible megoldas. (mintha az ossz kave termeles csak 100 lenne, de az ossz demand meg 150). Szoval csinalj tesztnek valami nagyon pici bemenetet, amire tudod, hogy van feasible megoldas. Aztan azok a lepesek, amiket irtam.

**Comment by raczmate** [comment]
Megnéztem, sikerült valid megoldást csinálnom.
Így elvileg pont a kereslet-kínálat dolog volt a probléma. Köszönöm az útmutatást!
